version: '3.9'

services:
  retroarch:
    container_name: retroarch
    image: kasmweb/retroarch:1.13.0
    ports:
      - 4901:4901
      - 5901:5901
      - 6901:6901
    environment:
      - VNC_PW=password
    command: --shm-size=512m